// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evkvbgnwuurkmllahqtb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2a3ZiZ253dXVya21sbGFocXRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1ODA2OTAsImV4cCI6MjA2NDE1NjY5MH0.Gab1UIHwFpdWCuPVs3FytLFhHMAq2NlbOsa9xG0ajYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);